/**
 * Lead Enrichment App
 * 
 * Enriches contacts and companies with structured sales data
 * Issue: #649
 */

import { callOllamaJson } from "../../dashboard/lib/llm.mjs";
import brain from "../../dashboard/lib/brain/index.mjs";

const META = {
  id: "lead-enrichment",
  name: "Lead Enrichment",
  description: "Enrich contacts and companies with structured sales data",
  category: "apps",
  issueId: "649"
};

async function enrichLead({ source, sourceData, enrichmentLevel = "standard", priority = "medium" }, repoRoot) {
  const leadId = "enriched_" + Math.random().toString(36).substring(2, 10);
  const now = new Date().toISOString();
  const expiresAt = new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString();

  let input = "";
  let prompt = "";

  if (source === "linkedin") {
    const profileUrl = sourceData.profileUrl || "";
    input = profileUrl;
    prompt = `You are a lead enrichment AI. Given a LinkedIn profile URL or username, generate a realistic professional profile.

Input: ${input}

Respond ONLY with a JSON object in this exact format:
{
  "name": "Full Name",
  "title": "Job Title",
  "company": "Company Name",
  "companySize": "51-200",
  "industry": "Technology",
  "location": "City, State",
  "linkedin": "${profileUrl.startsWith('http') ? profileUrl : 'https://linkedin.com/in/' + profileUrl}"
}

Make the data realistic and professional. No extra text, just JSON.`;
  } else if (source === "email") {
    const email = sourceData.email || "";
    input = email;
    const domain = email.split("@")[1] || "";
    prompt = `You are a lead enrichment AI. Given an email address, generate a realistic professional profile.

Input: ${input}
Domain: ${domain}

Respond ONLY with a JSON object in this exact format:
{
  "name": "Full Name",
  "title": "Job Title",
  "company": "${domain}",
  "location": "City, State",
  "email": "${email}"
}

Infer the name from the email prefix. Make data realistic. No extra text, just JSON.`;
  } else if (source === "company") {
    const domain = sourceData.domain || sourceData.company || "";
    input = domain;
    prompt = `You are a lead enrichment AI. Given a company domain, generate a realistic company profile.

Input: ${input}

Respond ONLY with a JSON object in this exact format:
{
  "company": "Company Name",
  "domain": "${domain}",
  "industry": "Technology",
  "companySize": "51-200"
}

Make data realistic. No extra text, just JSON.`;
  } else if (source === "phone") {
    input = sourceData.phone || "";
    prompt = `You are a lead enrichment AI. Given a phone number, generate a realistic profile.

Input: ${input}

Respond ONLY with a JSON object in this exact format:
{
  "phone": "${input}",
  "location": "City, State"
}

No extra text, just JSON.`;
  } else {
    return { ok: false, error: `Unknown or unsupported lead source: ${source}` };
  }

  if (!prompt.trim()) {
    return { ok: false, error: "Unknown or unsupported lead source." };
  }

  try {
    const result = await callOllamaJson(prompt, { model: "qwen3.5:0.8b", taskType: "enrich" });
    const profile = result.data;

    if (!profile || Object.keys(profile).length === 0) {
      return { ok: false, error: "Failed to parse LLM response as JSON. Raw response: " + result.raw.substring(0, 200) };
    }

    await brain.log(repoRoot, `Enriched lead: ${source} -> ${JSON.stringify(profile).substring(0, 50)}...`).catch(() => {});

    const signals = [
      { type: "ai_enriched", confidence: 0.78, detail: "Profile generated by local LLM (qwen3.5)" }
    ];

    if (enrichmentLevel === "full") {
      signals.push({ type: "full_enrichment", confidence: 0.85, detail: "Full enrichment with AI" });
    }

    const companySize = profile.companySize || "";
    const computedPriority = companySize.includes("1000") || companySize.includes("+") ? "high" : priority;

    return {
      ok: true,
      lead: {
        id: leadId,
        source,
        sourceData,
        profile,
        signals,
        priority: computedPriority,
        enrichedAt: now
      },
      audit: {
        enrichmentSources: [source, "ollama/qwen3.5:0.8b"],
        confidence: enrichmentLevel === "full" ? 0.85 : 0.78,
        expiresAt
      }
    };
  } catch (error) {
    return {
      ok: false,
      error: `LLM enrichment failed: ${error.message}`
    };
  }
}

async function handleApi(req, body, repoRoot) {
  const source = String(body.source || "");
  const sourceData = body.sourceData || {};
  const enrichmentLevel = String(body.enrichmentLevel || "standard");
  const priority = String(body.priority || "medium");

  if (!source || !sourceData || Object.keys(sourceData).length === 0) {
    return { ok: false, error: "Missing required fields: source and sourceData" };
  }

  return enrichLead({ source, sourceData, enrichmentLevel, priority }, repoRoot);
}

export {
  META,
  handleApi,
  enrichLead
};
